export const beginner = [
  { id: "1", name: "Bin2Dec1" },
  { id: "2", name: "Border Radius Previewer" },
  { id: "3", name: "Calculator" },
  { id: "4", name: "Christmas Lights" },
  { id: "5", name: "Cause Effect App" },
  { id: "6", name: "Color Cycle" },
  { id: "7", name: "Countdown Timer" },
  { id: "8", name: "CSV2JSON App" },
  { id: "9", name: "Dollars to Cents" },
  { id: "10", name: "Dynamic CSS Variables" },
  { id: "11", name: " First DB App	" },
  { id: "12", name: "Flip Image" },
  { id: "13", name: "GitHub Status" },
  { id: "14", name: "IOT Mailbox Simulator" },
  { id: "15", name: "JS Input Validation" },
  { id: "16", name: "JSON2CSV App" },
  { id: "17", name: "Key Value" },
  { id: "18", name: "Lorem Ipsum Generator" },
  { id: "19", name: "Notes App" },
  { id: "20", name: "Pearson Regression" },
  { id: "21", name: "Pomodoro Clock" },
  { id: "22", name: "Product Landing Page" },
  { id: "23", name: "Quiz App" },
  { id: "24", name: "Random Meal Generator" },
  { id: "25", name: "Random Number Generator" },
  { id: "26", name: "Roman to Decimal Converter" },
  { id: "27", name: "Slider Design" },
  { id: "28", name: "Stopwatch App" },
  { id: "29", name: "TrueOrFalse" },
  { id: "30", name: "Vigenere Cipher" },
  { id: "31", name: "Wind Chill" },
  { id: "32", name: "Word Frequency" },
  { id: "33", name: "Weather App" },
];

export const intermediate = [
  { id: "1", name: "Colors" },
  { id: "2", name: "Colors" },
  { id: "3", name: "Colors" },
];

export const advanced = [
  { id: "1", name: "Colors" },
  { id: "2", name: "Colors" },
  { id: "3", name: "Colors" },
];
